"""
Incident model.

An incident is a correlated group of related anomalies that together
represent one real engineering problem.

Example:
  10:01 — Anomaly: payment-service P95 latency spike (HIGH)
  10:02 — Anomaly: payment-service error rate spike (CRITICAL)
  10:03 — Anomaly: payment-service traffic drop (MEDIUM)

  All three belong to the same incident:
  INC-042: "Payment Service Degradation" — CRITICAL — OPEN

Why incidents instead of just anomalies?
  Without correlation, an engineer gets 3 pages at 2am.
  With correlation, they get 1 incident with full context.
  This is the primary engineering value of PulseOps over simple alerting.

Status lifecycle:
  OPEN          → newly created, not yet seen by a human
  ACKNOWLEDGED  → engineer has seen it, assigning someone to investigate
  INVESTIGATING → actively being worked on
  RESOLVED      → metrics returned to normal, incident closed

The `affected_endpoints` column stores a JSON array of endpoint paths
as a denormalized snapshot (e.g. ["/api/payment/process"]).
This avoids a join through anomalies → endpoints on every incident list query.

Severity is computed from the highest-severity anomaly in the group.

Relationships:
  Incident → Anomaly          (one-to-many, via anomaly.incident_id)
  Incident → IncidentEvidence (one-to-one)
  Incident → AiExplanation    (one-to-one)
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Index, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class Incident(Base):
    __tablename__ = "incidents"

    __table_args__ = (
        # Dashboard query: "all open incidents for project X, newest first"
        Index(
            "ix_incident_project_status_started",
            "project_id",
            "status",
            "started_at",
            postgresql_ops={"started_at": "DESC"},
        ),
        # Filter by severity
        Index("ix_incident_severity", "severity"),
    )

    # ── Primary key ───────────────────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True,
    )

    # ── Scope ─────────────────────────────────────────────────────────────────
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    service_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("services.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        # Primary affected service.
        # Multi-service incidents are a V2 concern.
    )

    # ── Identity ──────────────────────────────────────────────────────────────
    title: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
        # Auto-generated by the correlator, e.g.:
        # "payment-service: P95 latency + error rate anomaly"
    )

    # ── Denormalized snapshot ─────────────────────────────────────────────────
    affected_endpoints: Mapped[list] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
        # Array of affected endpoint paths, e.g.:
        # ["/api/payment/process", "/api/payment/status/{id}"]
        # Updated by the correlator when new anomalies are added.
        # JSONB gives us array operators and indexing in PostgreSQL.
    )

    # ── Classification ────────────────────────────────────────────────────────
    severity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="LOW",
        # "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"
        # = max severity across all linked anomalies
    )
    status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="OPEN",
        index=True,
        # "OPEN" | "ACKNOWLEDGED" | "INVESTIGATING" | "RESOLVED"
    )

    # ── Lifecycle timestamps ──────────────────────────────────────────────────
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        # Timestamp of the first anomaly that triggered this incident.
    )
    acknowledged_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # ── Human notes ───────────────────────────────────────────────────────────
    notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        # Free-text field for engineer notes during investigation.
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    anomalies: Mapped[list["Anomaly"]] = relationship(
        "Anomaly",
        back_populates="incident",
        # No cascade delete — anomalies outlive incidents for audit purposes.
        foreign_keys="[Anomaly.incident_id]",
    )
    evidence: Mapped["IncidentEvidence | None"] = relationship(
        "IncidentEvidence",
        back_populates="incident",
        uselist=False,          # one-to-one
        cascade="all, delete-orphan",
    )
    ai_explanation: Mapped["AiExplanation | None"] = relationship(
        "AiExplanation",
        back_populates="incident",
        uselist=False,          # one-to-one
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return (
            f"<Incident id={self.id} "
            f"severity={self.severity} "
            f"status={self.status}>"
        )
